### PR TITLE
Rename `incremental` to `counter`

### PR DESCRIPTION
**Pull request by mmazur**
Per https://github.com/OpenSLO/OpenSLO/pull/65

### CODE REVIEW

**Comment by nobl9-mikec** [comment]
Sorry about the failing `lint` @mmazur  - could you re-base from main and try again? Just merged a fix for the `Error: G304: Potential file inclusion via variable (gosec)` issue

**Review by nobl9-mikec — APPROVED** [review]

**Comment by mmazur** [comment]
Rebased

**Comment by nobl9-mikec** [comment]
Hmm..I'm not sure why the rebase didn't work.  Is it alright if I check out your branch and lint it / push any obvious fix I see @mmazur ?

**Comment by mmazur** [comment]
Sure, please apply this change however actually works :)

**Pull request merged**
