### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by kenfinnigan**
Fixes broken tests as a result of https://github.com/OpenSLO/oslo/pull/162 and https://github.com/OpenSLO/oslo/pull/163

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Does anyone know why the CI Checks didn't trigger with this PR?

**Comment by kenfinnigan** [comment]
Thanks @programmer04, what was the issue?

**Comment by programmer04** [comment]
I closed and reopened PR. CI has been triggered @kenfinnigan 🎉

**Review by programmer04 — APPROVED** [review]
🚀 thanks for the fix

**Comment by ian-bartholomew** [comment]
Thanks @kenfinnigan my bad for not following up on this.

**Comment by kenfinnigan** [comment]
No problem @ian-bartholomew, happy to help

**Pull request merged**
