### PR TITLE
Update Oslo to use Go structs from OpenSLO

### PR DESCRIPTION
**Pull request by kenfinnigan**
- Moved `v1alpha` structs to OpenSLO spec project
- Modified validation logic to utilize structs from OpenSLO spec project
- Added tests for `v1beta1` of spec

### CODE REVIEW

**Review by ian-bartholomew — COMMENTED** [review]
@kenfinnigan This looks good, just a  couple of build issues

**Review by ian-bartholomew — COMMENTED** [review]
Actually, @kenfinnigan i just noticed that you are pulling from `github.com/OpenSLO/OpenSLO/pkg/model/v1alpha` but the OpenSLO project doesn't have these, they are only here in oslo

**Comment by ian-bartholomew** [comment]
@kenfinnigan disregard my comments, i missed https://github.com/OpenSLO/OpenSLO/pull/113

**Comment by kenfinnigan** [comment]
Closing this for now until we finalize how we're defining schemas, etc

**Pull request closed without merging**
